disciple-tools-autolink.php
The plugin URI is used for plugin update checks.
=> Fix plugin URI

composer.lock, composer.scoped.lock, resources/views/partials/tools-menu.php, routes/web.php
commite to swap genmap mygroups
=> swap genmap mygroups

composer.json, composer.lock, composer.scoped.lock, resources/views/groups/modal.php, resources/views/groups/share-field.php, src/Controllers/GroupController.php, src/helpers.php
commite to the add church health circle
=> add the church health circle

resources/views/groups/form.php, resources/views/groups/modal.php, resources/views/groups/share-field.php, resources/views/partials/greeting.php, src/helpers.php
=> group share link 2

resources/js/genmapper.js
=> refresh genmap

resources/js/components/_churches.js, resources/views/groups/form.php, src/Controllers/FieldController.php, src/Controllers/GroupController.php
---
- https://app.asana.com/0/0/1209106267966504
=> Resolve the model issue in Genmap when a group is clicked

src/Providers/AssetServiceProvider.php
…once" error.
---
- https://app.asana.com/0/0/1209106270077155
=> Clicking the delete option on the My Group page returns an "Invalid nonce" error.

resources/views/groups/page.php
---
- https://app.asana.com/0/0/1209106267966508
=> Clicking the Add button on the MyGroup page results in an error.

config/services.php, src/Providers/DtMenuServiceProvider.php
---
- https://app.asana.com/0/0/1209156196504091
=> "Add main DT menu link" option is not working

cypress/e2e/cases/RT005_user_can_access_frontend_genmap_view.cy.js, cypress/e2e/cases/RT006_user_can_access_frontend_coaching_tree_view.cy.js, cypress/e2e/cases/RT007_user_can_access_frontend_my_groups_view.cy.js, cypress/e2e/cases/RT008_user_can_access_frontend_training_view.cy.js
---
- https://app.asana.com/0/0/1209158479329802
- https://app.asana.com/0/0/1209158479329804
=> Added Cypress Test Cases: RT005, RT006, RT007 & RT008

cypress/e2e/cases/RT003_admin_enables_showing_nested_vertical_genmap_settings_option.cy.js, cypress/e2e/cases/RT004_admin_disables_showing_nested_vertical_genmap_settings_option.cy.js, resources/js/church-circles-genmap.js, resources/js/genmapper.js, resources/views/genmap.php, resources/views/settings/general.php, routes/web.php, src/Controllers/Admin/GeneralSettingsController.php, src/Controllers/GenMapController.php, src/Services/Charts/GenmapChart.php
---
- https://app.asana.com/0/0/1209192663421516
=> Support Switching Of GenMap Charts Between Church Circles & Tree Views

src/Controllers/TrainingController.php
---
- https://app.asana.com/0/0/1209156196504094
=> The training videos that were added are not showing.

resources/css/_variables.css, resources/js/components/_ajax-field.js, src/Controllers/GroupController.php
---
- https://app.asana.com/0/0/1209165594273753
=> "Allow parent group selection" is not working

cypress/e2e/cases/RT009_user_can_copy_shared_autolink.cy.js
---
- https://app.asana.com/0/0/1209158479329806
=> Cypress Test Cases [RT009]

resources/js/components/_churches.js, resources/js/plugin.js
---
- https://app.asana.com/0/0/1209201424305161
=> fix User Group delete confirmation issue

cypress/e2e/cases/RT001_admin_allows_parent_group_selection_settings_option.cy.js, cypress/e2e/cases/RT002_admin_adds_main_dt_menu_link_settings_option.cy.js
---
- https://app.asana.com/0/0/1209158479329796
=> Cypress Test Cases [RT001 - 2]

cypress/e2e/cases/RT012_user_can_edit_group.cy.js, cypress/e2e/cases/RT013_user_can_delete_group.cy.js
---
- https://app.asana.com/0/0/1209158481555817
=> Cypress Test Cases [RT012 - 13]

cypress/e2e/cases/RT010_user_can_create_group.cy.js, cypress/e2e/cases/RT011_user_can_view_group.cy.js
---
- https://app.asana.com/0/0/1209158479329808
=> Cypress Test Cases [RT010 - 11]

cypress/e2e/cases/RT014_user_can_go_to_dt_from_menu.cy.js, cypress/e2e/cases/RT015_user_can_update_survey_answers_from_menu.cy.js, cypress/e2e/cases/RT016_user_can_logout_from_menu.cy.js
---
- https://app.asana.com/0/0/1209158481555819
=> Cypress Test Cases [RT014 - 16]

cypress/e2e/cases/RT018_admin_can_create_training_video_and_confirm_video_displayed_frontend.cy.js, cypress/e2e/cases/RT019_admin_can_move_training_video_up_and_down_and_confirm_its_display_on_frontend.cy.js
---
- https://app.asana.com/0/0/1209201424305163
=> Cypress Test Cases [RT018-19]

src/Controllers/SurveyController.php
---
- https://app.asana.com/0/0/1209211511138828
=> Analytics: Capture frontend update survey answers event.

resources/css/_app.css, resources/js/plugin.js, resources/views/partials/greeting.php, src/Controllers/GenMapController.php, src/Controllers/SurveyController.php
---
- https://app.asana.com/0/0/1204155889945061
=> Message included when copying link

resources/js/components/_menu.js, resources/views/layouts/app.php, routes/api.php, src/Controllers/LanguageController.php, src/Services/Language.php
---
- https://app.asana.com/0/0/1205268127312965
=> Add Change Language feature to the hamburger menu

src/Controllers/RegisterController.php, src/Repositories/UserRepository.php
---
- https://app.asana.com/0/0/1209337622150710
=> Fix Survey Submission Error After Account Registration

src/Controllers/LoginController.php, src/Services/Language.php
---
- https://app.asana.com/0/0/1209470234755470
=> Display Login Error Message on AutoLink Without Redirection

resources/css/admin.css, resources/js/admin.js, resources/js/components/_menu.js, resources/views/settings/general.php
---
- https://app.asana.com/0/0/1209492967246419
=> Fix Responsive Style for Language Dropdown on iOS Devices

resources/js/dom-hooks/_church-counts.js
---
- https://app.asana.com/0/0/1204155889944997
=> Count fields allow scientific notation
